[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*"
  [headers.values]
    Link = '''</fonts/Cooper%20BT/CooperBT-Regular.woff2>; rel=preload; as=font; type="font/woff2"; crossorigin, </fonts/sofia-pro/SofiaPro-Regular.woff2>; rel=preload; as=font; type="font/woff2"; crossorigin'''
